version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=yamanote.proxy.rlwy.net
      - PMA_PORT=37086
      - PMA_USER=root
      - PMA_PASSWORD=FtAnRejlbNVObUSdmmbDfySRXjdNbNlt